#!/bin/bash
#
# Silly script for cleaning all the files generated by autogen.sh
#

CLEAN_FILES="autom4te.cache aclocal.m4 config.h.in config.log config.guess.backup config.sub.backup configure config.sub depcomp missing install-sh ltmain.sh compile config.guess"
echo Cleaning $CLEAN_FILES and Makefile.in files
rm -rf $CLEAN_FILES
find . -name "Makefile.in" -exec rm -f {} \;
find . -name "*.~" -exec rm -f {} \;